//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Registration_id { get; set; }
        public string Firstname { get; set; }
        public string lastname { get; set; }
        public string nicname { get; set; }
        public int Course_ID { get; set; }
        public int Batch_ID { get; set; }
        public Nullable<long> Telephoneno { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
    }
}
